---
# rust-psbt CI
#
# CI job and task structure is optimized for developer debugging. Not runner
# minutes or parallelism.

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

name: Continuous Integration

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly, msrv]
        dep: [minimal, recent]
    steps:
      - uses: actions/checkout@v6
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@18e7f1788abfc14f5fb76204a3deab43b03ba39c
      - name: "Run tests"
        run: cargo rbmt --lock-file ${{ matrix.dep }} test --toolchain ${{ matrix.toolchain }}

  Check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [lint, api, docs, docsrs, integration, "fmt --check"]
    steps:
      - uses: actions/checkout@v6
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/setup-rbmt@18e7f1788abfc14f5fb76204a3deab43b03ba39c
      - name: "Run ${{ matrix.command }}"
        run: cargo rbmt ${{ matrix.command }}
